[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew/" }

wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["HtmlCollection"] }

gloo = "0.8"
gloo-net = { version = "0.2.4", features = ["http", "json"] }
monaco = { git = "https://github.com/hamza1311/rust-monaco", branch = "yew-playground", features = ["yew-components"] }
tracing-web = "0.1.2"

anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1"

tracing = { version = "0.1", default-features = false }
time = { version = "0.3", features = ["wasm-bindgen"] }
tracing-subscriber = { version = "0.3", features = ["time"] }
