[[proxy]]
#rewrite = "/apis/"
backend = "http://localhost:3000/apis/"
#backend = "https://play.yew.rs/"

[serve]
# The address to serve on.
address = "0.0.0.0"
# The port to serve on.
port = 8080

[[hook]]
stage = "build"
command = "npm"
command_arguments = ["run", "build:tailwind"]
