[package]
name = "wasmtime_hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = {version="7.0.0"}
anyhow = "1.0.44"
lazy_static = "1.4.0"